# enforce mp4 video and m4a audio, or best available mp4
--format "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]"

# Uncomment to allow fallback to non-mp4
# --format "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b"

# strip non-ASCII characters
--restrict-filenames

# output filename format: "youtube_video_title_BaW_jenozKc.mp4". Will save in currenct directory unless otherwise specified
-o "%(title)s_%(extractor)s[%(id)s].%(ext)s"
