// Package port provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package port

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Handle  string `json:"handle"`
	Message string `json:"message"`
}

// Video defines model for Video.
type Video struct {
	Url string `json:"url"`
}

// PostV1VideosJSONRequestBody defines body for PostV1Videos for application/json ContentType.
type PostV1VideosJSONRequestBody = Video
